displayName: Rewrite Header for traefik
type: middleware
import: github.com/vincentinttsh/rewriteheaders

summary: Rewrites the HTTP response headers by replacing a search regex by a replacement string.

testData:
  rewrites:
    - header: Location
      regex: "^http://(.+)$"
      replacement: "https://$1"
